---
# tasks file for uat-nginx

- name: Install nginx
  yum:
    name: nginx 
    state: present

- name: Copy nginx configuration files
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Copy nginx configuration conf.d files
  template: 
    src=nginx/conf.d/{{ item.name }} 
    dest=/etc/nginx/conf.d/
  with_items:
    - { name: '1' }
    - { name: '2' }
    - { name: '3' }
  notify:
    Reload nginx configuration

- name: Make sure nginx is running
  service: name=nginx state=started enabled=yes
