
- name: modify ip forward configuration file
  template: src=50-default.conf dest=/usr/lib/sysctl.d/50-default.conf

- name: tune on ipv4 forward
  command: /sbin/sysctl -w net.ipv4.ip_forward=1

- name: MASQUERADE source ip address
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: eth0
    jump: MASQUERADE

- name: redirect dev-nginx
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination_port: 10002
    jump: DNAT
    to_destination: 10.1.1.10:22

- name: redirect dev-services
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination_port: 10003
    jump: DNAT
    to_destination: 10.1.100.10:22

- name: redirect dev-database
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination_port: 10004
    jump: DNAT
    to_destination: 10.1.101.10:22
